# Generated by Django 4.1.7 on 2023-04-11 13:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999'))])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karcianki.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('nickname', 'game_id'), name='unique nickname in game'),
        ),
    ]
