# Generated by Django 4.2.1 on 2023-05-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_chips', models.IntegerField(default=100)),
                ('pot', models.IntegerField(default=0)),
                ('last_raise', models.IntegerField(null=True)),
                ('stage', models.IntegerField(default=1)),
                ('dealer', models.IntegerField(default=0)),
                ('player_number', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('START', 'START'), ('TURN', 'TURN'), ('NEXT', 'NEXT'), ('END', 'END')], default='START', max_length=5)),
                ('last_bet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TGame',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('START', 'START'), ('TURN', 'TURN'), ('END', 'END')], default='START', max_length=5)),
                ('last_bet', models.IntegerField(default=100)),
                ('player100', models.IntegerField(default=0)),
                ('playing', models.IntegerField(default=0)),
                ('player_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('player_number', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('info', models.CharField(default='', max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karcianki.tgame')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('player_number', models.IntegerField(default=0)),
                ('chips', models.IntegerField(default=100)),
                ('last_bet', models.IntegerField(default=0)),
                ('info', models.CharField(default='', max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karcianki.game')),
            ],
        ),
    ]
