# Generated by Django 4.1.7 on 2023-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karcianki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('player_number', 'game_id'), name='unique player number in game'),
        ),
    ]
