# Generated by Django 4.2.1 on 2023-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karcianki', '0003_alter_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='start_chips',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=100),
        ),
    ]
