name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    - name: validate CSS
      run: |
        for f in $(find . -name 'src/*.css'); do
          yarn run stylelint $f
        done;
    - name: install dependencies
      run: |
        python -m pip install virtualenv
        python -m virtualenv .venv
        source .venv/bin/activate
        python -m pip install pytest
        python -m pip install selenium
        python -m pip install webdriver_manager
    - uses: browser-actions/setup-firefox@v1
    - name: run tests
      run: |
        source .venv/bin/activate
        python -m pytest tests --capture=sys