name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    - name: validate HTML
      run: |
        find . -name "*.html" -exec sh -c 'html-validate {}' \;
    - name: validate CSS
      run: |
        npx stylelint style.css
