name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    - name: validate CSS
      run: |
        for f in $(find . -name 'src/*.css'); do
          yarn run stylelint $f
        done;
    - uses: browser-actions/setup-firefox@v1
    - name: run tests
      run: |
        yarn run pytest tests --capture=sys