name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    # - name: validate CSS
    #   run: |
    #     for f in $(find karcianki/ -name '*.css'); do
    #       yarn run stylelint $f
    #     done;
    # - name: validate HTML
    #   run: |
    #     for f in $(find karcianki/ -name '*.html'); do
    #       yarn run html-validate $f
    #     done;
    # - name: validate Python
    #   run: |
    #       pylint karcianki/
    - uses: browser-actions/setup-firefox@v1
    - name: run server
      run: |
        python3 manage.py runserver & sleep 10
    - name: run tests
      run: |
        yarn test
    - name: Upload coverage reports to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v3
