name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    - name: install dependencies
      run: |
        pip install pytest
        pip install selenium
        pip install webdriver_manager
        pip install pytest-cov
    - name: validate CSS
      run: |
        for f in $(find src/ -name '*.css'); do
          yarn run stylelint $f
        done;
    - name: validate HTML
      run: |
        for f in $(find src/ -name '*.html'); do
          yarn run html-validate $f
        done;
    - uses: browser-actions/setup-firefox@v1
    - name: run tests
      run: |
        yarn test
    - name: Upload coverage reports to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v3
