name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: |
        yarn install
    - name: validate HTML
      run: |
        for f in $(find . -name '*.html'); do
          html-validate $f;
        done;
    - name: validate CSS
      run: |
        npx stylelint style.css
